(function(){
  // ── Hamburger nav toggle ──────────────────────────────
  var nav = document.querySelector('.site-nav');
  var btn = document.querySelector('.nav-toggle');
  if(btn){
    btn.addEventListener('click', function(){
      nav.classList.toggle('nav-open');
    });
    document.querySelectorAll('.nav-links a').forEach(function(a){
      a.addEventListener('click', function(){
        nav.classList.remove('nav-open');
      });
    });
  }

  // ── Lazy-load images below the fold ──────────────────
  document.querySelectorAll('img').forEach(function(img){
    var aboveFold = img.closest('.hero-media') || img.closest('.page-hero');
    if(!aboveFold) img.loading = 'lazy';
  });

  // ── i18n ─────────────────────────────────────────────
  var T = {
    it: {
      // NAV
      'nav.home':'Home','nav.about':'Chi Siamo','nav.experience':'Esperienza',
      'nav.stalls':'Mostre','nav.visit':'Visita','nav.contact':'Contatti','nav.cta':'Visita',
      // FOOTER
      'footer.brand.desc':'Bindi to Brera è una mostra culturale indiana contemporanea a Milano che esplora artigianato, memoria sensoriale, intelligenza materiale e design partecipativo.',
      'footer.h.experience':'Esperienza','footer.link.overview':'Panoramica',
      'footer.link.craft':'Esperienze Artigianali','footer.link.material':'Esplorazioni Materiali',
      'footer.link.stage':'Palco Principale',"footer.link.food":"Sapori d'India",
      'footer.h.visit':'Visita','footer.link.info':'Info Evento','footer.link.venue':'Sede','footer.link.faq':'FAQ',
      'footer.h.connect':'Connettiti','footer.link.contact':'Contattaci',
      'footer.link.partners':'Partnership','footer.link.about':'Chi Siamo',
      'footer.date':'Milano, Italia | 11-12 Luglio 2026',
      // INDEX
      'index.hero.eyebrow':'Milano | 11-12 Luglio 2026',
      'index.hero.lead':"Una mostra culturale contemporanea che reinterpreta l'India attraverso artigianato, narrazione sensoriale, intelligenza materiale e design immersivo.",
      'index.hero.meta.venue':'Sede','index.hero.meta.format':'Formato','index.hero.meta.admission':'Ingresso',
      'index.hero.meta.format.val':'Mostra Curata','index.hero.meta.admission.val':'Ingresso Libero',
      'index.why.eyebrow':'Perché Bindi to Brera','index.why.h2':'Non Geografia.<br>Percezione.',
      'index.why.p1':'Bindi to Brera non è una dichiarazione geografica, ma di percezione.',
      'index.why.p2':"Ospitata a Fabbrica del Vapore, la parola Brera simboleggia artigianato, raffinatezza, sofisticazione artistica e un'esperienza culturale di alto livello.",
      'index.why.p3':"La mostra sfida gli stereotipi sull'India reinterpretandola attraverso la cultura materiale, la narrazione sensoriale, l'artigianato e il design immersivo.",
      'index.why.p4':'Bindi rappresenta identità, intimità e simbolismo culturale. Brera rappresenta curatela, lusso e valore artistico elevato. Insieme, creano un ponte tra patrimonio e percezione contemporanea.',
      'index.encounters.eyebrow':'Mostre ed Esperienze Immersive','index.encounters.h2':'Incontri Curati',
      'index.card.craft.tag':'Esperienze Artigianali','index.card.craft.h3':'Mani, Processo, Tessuto',
      'index.card.craft.p':"Stampa con blocchi, ceramica, calligrafia, drappeggio del sari, styling con bandana riciclata, partecipazione al muro di rangoli e l'esperienza del bindi.",
      'index.card.material.tag':'Esplorazioni Materiali','index.card.material.h3':'Archivio, Ingrediente, Memoria',
      'index.card.material.p':'Archivio delle Spezie, Camera delle Fragranze, Prodotti Ayurvedici e Strumenti Musicali presentati come cultura materiale piuttosto che spettacolo.',
      'index.card.womb.tag':'Installazione Immersiva',
      'index.card.womb.p':"Un tunnel immersivo di origine, vibrazione, transizione spaziale e riflessione ispirato all'architettura e alla filosofia sonora.",
      'index.card.stage.tag':'Programma Live','index.card.stage.h3':'Palco Principale',
      'index.card.stage.p':"Cerimonia di apertura con il Console Generale dell'India, danza classica Kathak e Bharatanatyam, medley Bollywood e musica live Sitar & fusion.",
      'index.card.food.tag':'Esperienza Culinaria',
      'index.card.food.p':"Street food regionale con bancarelle del Nord, Sud, Est e Ovest dell'India, con un angolo Masala Chai e dolci tradizionali indiani.",
      'index.btn.stalls':'Esplora le Mostre','index.btn.experience':"Scopri l'Esperienza",
      'index.visual.eyebrow':'Linguaggio Visivo','index.visual.h2':'Minimale.<br>Ricco.<br>Editoriale.',
      'index.visual.p':"Il sito utilizza una palette contenuta di nero, crema, terra opaca, indaco e accenti metallici. L'atmosfera si avvicina a una mostra di lusso, un'installazione di moda e un museo culturale più che a un evento.",
      'index.visit.h2':'Pianifica la Tua Visita',
      'index.visit.lead':"Due giorni a Milano dedicati all'artigianato, alla memoria materiale e alla percezione culturale indiana contemporanea.",
      'index.btn.visit':'Dettagli Visita','index.btn.contact':'Contattaci',
      'index.marquee.1':'Artigianato','index.marquee.2':'Cultura Materiale','index.marquee.3':'Design Indiano',
      'index.marquee.4':'Memoria Sensoriale','index.marquee.5':'Esperienze Partecipative',
      'index.marquee.6':'Artigianato','index.marquee.7':'Cultura Materiale','index.marquee.8':'Design Indiano',
      'index.marquee.9':'Memoria Sensoriale','index.marquee.10':'Esperienze Partecipative',
      // ABOUT
      'about.hero.eyebrow':'La Mostra',
      'about.hero.lead':"Una mostra culturale contemporanea che reinterpreta l'India attraverso artigianato, narrazione sensoriale, intelligenza materiale e design immersivo.",
      'about.name.eyebrow':'Il Nome','about.name.h2':'Identità Incontra<br>Curatela',
      'about.name.p1':'Bindi rappresenta identità, intimità e simbolismo culturale.',
      'about.name.p2':'Brera rappresenta curatela, lusso e valore artistico elevato.',
      'about.name.p3':"Insieme, creano un ponte tra patrimonio e percezione contemporanea. Il titolo non è intenzionalmente geografico; è un modo di cambiare come la cultura indiana viene vista, vissuta e valorizzata in un contesto di design europeo.",
      'about.quote':'"L\'India non è presentata come uno spettacolo da consumare, ma come un mondo materiale, sensoriale e intellettuale in cui entrare con attenzione."',
      'about.pos.eyebrow':'Posizionamento','about.pos.h2':'Chic.<br>Curata.<br>Museale.',
      'about.pos.p1':"La mostra si allontana dal linguaggio degli eventi decorativi verso un'esperienza editoriale, di alto livello e contemporanea. Il focus è il processo artigianale, la partecipazione raffinata, le storie degli ingredienti, l'atmosfera spaziale e l'intelligenza custodita nei materiali quotidiani.",
      'about.pos.p2':'I visitatori sono invitati a osservare, toccare, scrivere, stampare, vestire, ascoltare e riflettere attraverso incontri progettati piuttosto che esposizioni decorative.',
      'about.lenses.eyebrow':'Prospettive Chiave','about.lenses.h2':"Come l'India Viene Reinterpretata",
      'about.card.craft.tag':'Artigianato','about.card.craft.h3':'Mani e Processo',
      'about.card.craft.p':'I workshop rivelano la disciplina del fare: pressione, ritmo, argilla, tessuto, scrittura e ornamento personale.',
      'about.card.material.tag':'Cultura Materiale','about.card.material.h3':'Ingredienti come Archivi',
      'about.card.material.p':'Spezie, botaniche, ingredienti per fragranze e strumenti sono inquadrati come storie di agricoltura, commercio, benessere e performance.',
      'about.card.immersion.tag':'Immersione','about.card.immersion.h3':'Spazio e Memoria',
      'about.card.immersion.p':'The Womb of OM crea una transizione spaziale attraverso vibrazione, origine, riflessione e narrazione architettonica.',
      'about.navarasa.eyebrow':'Le Nove Rasa','about.navarasa.h2':'Divisione per<br>Emozione',
      'about.navarasa.intro':"La mostra è strutturata intorno alle nove Rasa — sanscrito per essenze emotive. Ogni stand ed esperienza si connette a uno o più di questi stati, trasformando la visita in un viaggio emotivo attraverso la filosofia culturale indiana.",
      'about.rasa.srngara.h3':'Bellezza','about.rasa.srngara.p':'Gioielleria, Bindi, Drappeggio del Sari, Profumo.',
      'about.rasa.hasya.h3':'Gioco e Gioia','about.rasa.hasya.p':'Stampa con Blocchi, Bandana Riciclata.',
      'about.rasa.karuna.h3':'Dolcezza e Cura','about.rasa.karuna.p':'Prodotti Ayurvedici, Ceramica.',
      'about.rasa.raudra.h3':'Intensità e Calore','about.rasa.raudra.p':'Archivio delle Spezie.',
      'about.rasa.vira.h3':'Energia e Maestria','about.rasa.vira.p':'Stampa con Blocchi, Drappeggio del Sari, Calligrafia.',
      'about.rasa.bhayanka.h3':'Meraviglia e Stupore','about.rasa.bhayanka.p':'The Womb of OM.',
      'about.rasa.adhbutha.h3':'Stupore e Scoperta','about.rasa.adhbutha.p':'Strumenti Musicali, Stampa con Blocchi, Calligrafia.',
      'about.rasa.bibhatsa.h3':'Verità Materiale Grezza','about.rasa.bibhatsa.p':'Spezie, Ceramica, Ingredienti Ayurvedici grezzi.',
      'about.rasa.santa.h3':'Calma ed Equilibrio','about.rasa.santa.p':'Prodotti Ayurvedici.',
      'about.notfair.h2':'Non una Fiera.<br>Una Mostra.',
      'about.notfair.p':"La direzione aggiornata utilizza interpretazione culturale raffinata, ritmo visivo contenuto e partecipazione del visitatore con uno scopo. L'esperienza è ora strutturata intorno all'intelligenza artigianale, alla cultura materiale e alla percezione contemporanea.",
      'about.btn.experience':"Panoramica dell'Esperienza",
      // EXPERIENCE
      'exp.hero.eyebrow':'Il Quadro Emotivo','exp.hero.h1':'Nove<br>Rasa',
      'exp.hero.p':"La mostra è strutturata intorno alle nove Rasa — essenze emotive sanscrite della filosofia estetica indiana. Ogni stand, workshop e installazione corrisponde a uno o più di questi stati.",
      'exp.what.eyebrow':"Cos'è una Rasa",'exp.what.h2':'Sentire<br>come<br>Framework',
      'exp.what.p1':"Rasa — sanscrito per «essenza» o «sapore» — è un concetto estetico indiano di 2.000 anni che descrive gli stati emotivi che l'arte e l'esperienza possono evocare. Le nove Rasa costituiscono la base delle arti performative classiche indiane, della poesia e del design.",
      'exp.what.p2':"Bindi to Brera usa questo framework per organizzare la mostra. Ogni incontro — dalla stampa con blocchi al Womb of OM — è intenzionalmente collocato in un registro emotivo. Il risultato non è un'esposizione culturale ma un viaggio emotivo attraverso la filosofia estetica indiana.",
      'exp.btn.stalls':'Esplora Tutte le Mostre',
      'exp.rasas.eyebrow':'I Nove Stati Emotivi','exp.rasas.h2':'Le Rasa',
      'exp.rasa.srngara.h3':'Bellezza',
      'exp.rasa.srngara.p':"La rasa dell'ornamento, dell'intimità e del piacere sensoriale. Il mondo visto attraverso la lente della bellezza e del desiderio.",
      'exp.rasa.srngara.links':'→ <a href="stalls.html#jewellery" style="color:inherit">Gioielleria Indiana</a> · <a href="stalls.html#bindi" style="color:inherit">Bindi &amp; Tatuaggio</a> · <a href="stalls.html#saree" style="color:inherit">Drappeggio del Sari</a> · <a href="stalls.html#fragrance-chamber" style="color:inherit">Camera delle Fragranze</a>',
      'exp.rasa.hasya.h3':'Gioco e Gioia',
      'exp.rasa.hasya.p':"La rasa della risata, della leggerezza e della creazione giocosa — quando fare errori diventa parte della gioia.",
      'exp.rasa.hasya.links':'→ <a href="stalls.html#block" style="color:inherit">Stampa con Blocchi</a> · <a href="stalls.html#bandana" style="color:inherit">Bandana Riciclata</a>',
      'exp.rasa.karuna.h3':'Dolcezza e Cura',
      'exp.rasa.karuna.p':"La rasa della compassione e della tenerezza — il processo terapeutico del fare, guarire e nutrire.",
      'exp.rasa.karuna.links':'→ <a href="stalls.html#ayurvedic-products" style="color:inherit">Prodotti Ayurvedici</a> · <a href="stalls.html#pottery" style="color:inherit">Ceramica</a>',
      'exp.rasa.raudra.h3':'Intensità e Calore',
      'exp.rasa.raudra.p':"La rasa della forza, della passione e dell'energia grezza — il calore e il potere travolgenti del mondo materiale indiano.",
      'exp.rasa.raudra.links':'→ <a href="stalls.html#spice-archive" style="color:inherit">Archivio delle Spezie</a>',
      'exp.rasa.vira.h3':'Energia e Maestria',
      'exp.rasa.vira.p':"La rasa dell'abilità, della fiducia e dell'azione disciplinata — l'artigianato eseguito con precisione e potere trasformativo.",
      'exp.rasa.vira.links':'→ <a href="stalls.html#block" style="color:inherit">Stampa con Blocchi</a> · <a href="stalls.html#saree" style="color:inherit">Drappeggio del Sari</a> · <a href="stalls.html#calligraphy" style="color:inherit">Calligrafia</a>',
      'exp.rasa.bhayanka.h3':"Meraviglia e l'Ignoto",
      'exp.rasa.bhayanka.p':"La rasa del sopraffacimento e del mistero — il confronto con qualcosa di più grande di sé.",
      'exp.rasa.bhayanka.links':'→ <a href="stalls.html#womb-of-om" style="color:inherit">The Womb of OM</a>',
      'exp.rasa.adhbutha.h3':'Stupore e Scoperta',
      'exp.rasa.adhbutha.p':"La rasa dello stupore — quando emerge uno schema, un linguaggio si trasforma visivamente, un suono viene percepito fisicamente.",
      'exp.rasa.adhbutha.links':'→ <a href="stalls.html#musical-instruments" style="color:inherit">Strumenti Musicali</a> · <a href="stalls.html#block" style="color:inherit">Stampa con Blocchi</a> · <a href="stalls.html#calligraphy" style="color:inherit">Calligrafia</a>',
      'exp.rasa.bibhatsa.h3':'Verità Materiale Grezza',
      'exp.rasa.bibhatsa.p':"La rasa dell'non lavorato e non raffinato — la materia nel suo stato d'origine prima di diventare merce o lusso.",
      'exp.rasa.bibhatsa.links':'→ <a href="stalls.html#spice-archive" style="color:inherit">Archivio delle Spezie</a> · <a href="stalls.html#pottery" style="color:inherit">Ceramica</a> · <a href="stalls.html#ayurvedic-products" style="color:inherit">Prodotti Ayurvedici</a>',
      'exp.rasa.santa.h3':'Calma ed Equilibrio',
      'exp.rasa.santa.p':"La rasa della pace e dell'equanimità — riposo, reset sensoriale e il silenzio che segue il pieno coinvolgimento.",
      'exp.rasa.santa.links':'→ <a href="stalls.html#ayurvedic-products" style="color:inherit">Prodotti Ayurvedici</a>',
      'exp.ready.h2':'Pronto a<br>Esplorare?',
      'exp.ready.p':'Ogni stand e installazione si connette a uno o più di questi stati emotivi. Visita la directory completa delle mostre per vedere ogni esperienza in dettaglio.',
      'exp.btn.stalls2':'Vedi Tutte le Mostre','exp.btn.about':'Informazioni sulle Nove Rasa',
      // STALLS
      'stalls.hero.eyebrow':'Set di Esperienze Approvato','stalls.hero.h1':'Mostre ed<br>Esperienze<br>Immersive',
      'stalls.hero.p':'Un programma mirato di partecipazione artigianale, cultura materiale, suono, fragranza, conoscenza botanica e riflessione spaziale.',
      'stalls.craft.eyebrow':'Esperienze Artigianali','stalls.craft.h2':'Fare Partecipativo',
      'stalls.card.block.tag':'Workshop','stalls.card.block.h3':'Workshop di Stampa con Blocchi',
      'stalls.card.block.p':'Stampa tessile collaborativa dove i visitatori stampano da soli, sperimentano la pressione del blocco e contribuiscono a una superficie tessile condivisa.',
      'stalls.card.pottery.tag':'Creazione dal Vivo','stalls.card.pottery.h3':'Ceramica',
      'stalls.card.pottery.p':'Creazione dal vivo con argilla come narrazione attraverso artigianato, terra, mano, forma e tecnica ereditata.',
      'stalls.card.calligraphy.tag':'Scrittura','stalls.card.calligraphy.h3':'Calligrafia',
      'stalls.card.calligraphy.p':'Esplorazione delle lingue indiane con partecipazione dei visitatori attraverso scrittura, stencil e creazione di segni guidata.',
      'stalls.card.saree.tag':'Tessile','stalls.card.saree.h3':'Drappeggio del Sari',
      'stalls.card.saree.p':"Esplorazione contemporanea del drappeggio che tratta sei metri di tessuto come design, identità, scultura e movimento personale.",
      'stalls.card.bandana.tag':'Stile Sostenibile','stalls.card.bandana.h3':'Bandana Riciclata',
      'stalls.card.bandana.p':"Un'esperienza di stile sostenibile che utilizza il riutilizzo tessile per la sperimentazione della moda e l'espressione personale.",
      'stalls.card.rangoli.tag':'Installazione Murale','stalls.card.rangoli.h3':'Muro di Rangoli',
      'stalls.card.rangoli.p':"Un'installazione murale collettiva dove ogni visitatore contribuisce attraverso il posizionamento di adesivi, più una competizione pubblica di arte con la sabbia Rangoli aperta a tutte le età.",
      'stalls.card.bindi.tag':'Ornamento','stalls.card.bindi.h3':'Bindi e Tatuaggio Temporaneo',
      'stalls.card.bindi.p':"Stazione di bellezza interattiva con bindi in varie forme, colori e design, più piccoli motivi dipinti a mano intorno agli occhi e alla fronte ispirati all'hennè e all'arte indiana tradizionale.",
      'stalls.material.eyebrow':'Esplorazioni Materiali e Culturali','stalls.material.h2':'Archivi della Materia',
      'stalls.card.spice.tag':'Cultura Materiale','stalls.card.spice.h3':'Archivio delle Spezie',
      'stalls.card.spice.p':'Le spezie vengono presentate attraverso il patrimonio agricolo, il colore, la texture e il significato nel commercio globale.',
      'stalls.card.fragrance.tag':'Profumeria Naturale','stalls.card.fragrance.h3':'Camera delle Fragranze',
      'stalls.card.fragrance.p':'Ingredienti materiali, artigianalità, memoria e narrazione culturale attraverso la storia della fragranza.',
      'stalls.card.ayurveda.tag':'Conoscenza Botanica','stalls.card.ayurveda.h3':'Prodotti Ayurvedici',
      'stalls.card.ayurveda.p':"Tradizioni di bellezza e benessere presentate attraverso l'esplorazione degli ingredienti e il patrimonio materiale.",
      'stalls.card.music.tag':'Suono Interattivo','stalls.card.music.h3':'Strumenti Musicali',
      'stalls.card.music.p':'Artigianalità della costruzione di strumenti, risonanza, esplorazione del ritmo tattile, tradizioni performative e interazione con i visitatori.',
      'stalls.card.jewellery.tag':'Gioielleria','stalls.card.jewellery.h3':'Gioielleria Indiana',
      'stalls.card.jewellery.p':"Una collezione curata di gioielleria tradizionale e contemporanea — jhumkas, bracciali, cavigliere, anelli al naso e collane stratificate ispirate a diverse regioni dell'India.",
      'stalls.stage.eyebrow':'Programma Live','stalls.stage.h2':'Palco<br>Principale',
      'stalls.stage.p1':"Il fulcro dell'evento. Si apre con una cerimonia formale con il Console Generale dell'India e un rappresentante del Comune di Milano.",
      'stalls.stage.p2':'Seguono danza classica Kathak e Bharatanatyam, una troupe professionale di medley Bollywood e un ensemble live Sitar & musica fusion.',
      'stalls.stage.item1.h3':'Cerimonia di Apertura Solenne',
      'stalls.stage.item1.p':"Console Generale dell'India e rappresentante del Comune di Milano.",
      'stalls.stage.item2.h3':'Kathak e Bharatanatyam','stalls.stage.item2.p':'Performance di danza classica indiana.',
      'stalls.stage.item3.h3':'Troupe Medley Bollywood','stalls.stage.item3.p':'Performance Bollywood contemporanea professionale.',
      'stalls.stage.item4.h3':'Ensemble Sitar & Fusion','stalls.stage.item4.p':'Performance musicale dal vivo.',
      'stalls.food.eyebrow':'Esperienza Culinaria','stalls.food.h2':"Sapori<br>d'India",
      'stalls.food.p1':"Un'area in stile street food con bancarelle regionali del Nord, Sud, Est e Ovest dell'India. Un dialogo vivo tra il patrimonio culinario indiano e la cultura gastronomica milanese.",
      'stalls.food.p2':"Include un angolo Masala Chai e dolci tradizionali indiani. Tutti gli operatori dispongono di permessi alimentari validi e in tutta la manifestazione è richiesto l'uso di imballaggi ecologici.",
      'stalls.womb.eyebrow':'Installazione Immersiva','stalls.womb.h2':'The Womb<br>of OM',
      'stalls.womb.p1':"«OM» è trattato come la forma dell'universo — un ciclo continuo di creazione, esistenza e ritorno.",
      'stalls.womb.p2':"Ispirata alle antiche incisioni templari dove la vita emerge all'interno di forme di suono sacro, l'installazione riflette l'idea dell'origine custodita all'interno del simbolo stesso.",
      'stalls.womb.p3':'Il cordone ombelicale diventa il filo visivo della vita, collegando inizio e divenire in un flusso ininterrotto.',
      'stalls.womb.p4':"Lo stand trasforma questa idea in un'esperienza immersiva in cui il corpo attraversa cicli di nascita, crescita e ritorno.",
      // VISIT
      'visit.hero.eyebrow':'Pianifica la Tua Visita','visit.hero.h1':'Milano<br>2026',
      'visit.hero.p':'Tutti i dettagli pratici per partecipare a Bindi to Brera, una mostra pubblica gratuita alla Fabbrica del Vapore.',
      'visit.details.eyebrow':'Dettagli Evento','visit.details.h2':'11-12 Luglio<br>2026',
      'visit.detail.venue.label':'Sede','visit.detail.venue.val':'Fabbrica del Vapore o Parco Sempione, Milano (soggetto alla disponibilità del Comune)',
      'visit.detail.admission.label':'Ingresso','visit.detail.admission.val':'Ingresso pubblico gratuito',
      'visit.detail.format.label':'Formato','visit.detail.format.val':'Mostra pubblica multiculturale en plein air e al coperto',
      'visit.detail.focus.label':'Focus','visit.detail.focus.val':'Artigianato, cultura materiale, immersione',
      'visit.detail.audience.label':'Pubblico','visit.detail.audience.val':'Cittadini milanesi, pubblico italiano e i 50.000+ membri della diaspora indiana in Lombardia',
      'visit.detail.duration.label':'Durata','visit.detail.duration.val':'Due giorni',
      'visit.detail.attendance.label':'Presenze Attese','visit.detail.attendance.val':'2.000–5.000 visitatori',
      'visit.detail.patronage.label':'Patrocinio Civico','visit.detail.patronage.val':'Comune di Milano',
      'visit.expect.eyebrow':'Cosa Aspettarsi','visit.expect.h2':'Un Incontro<br>più Lento',
      'visit.expect.p1':"I visitatori possono spostarsi tra esperienze artigianali, esplorazioni materiali e culturali, le performance live del Palco Principale, il ristorante Sapori d'India e l'installazione Womb of OM. Il programma è progettato per un'osservazione attenta, una partecipazione accurata e un'interpretazione culturale contemporanea.",
      'visit.expect.p2':"Alcune esperienze pratiche potrebbero avere una capacità limitata nelle ore di punta, ma la mostra è costruita per una scoperta walk-in durante tutta la giornata.",
      'visit.faq.eyebrow':'FAQ','visit.faq.h2':'Buono a Sapersi',
      "visit.faq.free.h3":"L'ingresso è gratuito?",'visit.faq.free.p':'Sì. La mostra è gratuita e aperta al pubblico.',
      "visit.faq.venue.h3":"Dov'è la sede?",'visit.faq.venue.p':'La mostra è prevista alla Fabbrica del Vapore di Milano.',
      'visit.faq.book.h3':'Le esperienze sono prenotabili?','visit.faq.book.p':'La maggior parte delle esperienze è walk-in. La capacità può essere gestita in loco per comfort e qualità.',
      'visit.faq.time.h3':'Quanto tempo dovrei restare?','visit.faq.time.p':'Pianifica almeno due ore per il percorso principale, o di più se vuoi partecipare a diverse esperienze artigianali.',
      'visit.questions.h2':'Domande?','visit.questions.lead':'Per partnership, stampa o informazioni sui visitatori, contatta il team.',
      'visit.btn.contact':'Contattaci','visit.reg.h3':'Registra la Tua Visita',
      'visit.reg.name':'Nome','visit.reg.email':'Email','visit.reg.attendees':'Numero di Partecipanti','visit.reg.btn':'Registrati',
      // CONTACT
      'contact.hero.eyebrow':'Contatti','contact.hero.h1':'Collabora<br>Con Noi',
      'contact.hero.p':'Per partnership, stampa, richieste istituzionali o informazioni per i visitatori, contatta il team di Bindi to Brera.',
      'contact.info.eyebrow':'Informazioni di Contatto','contact.info.h2':'Connettiamoci',
      'contact.info.general.h3':'Richieste Generali','contact.info.support.h3':'Supporto',
      'contact.info.partners.h3':'Partnership','contact.info.location.h3':'Sede',
      'contact.info.location.val':'Fabbrica del Vapore, Milano | 11-12 Luglio 2026',
      'contact.form.name':'Nome','contact.form.email':'Email',
      'contact.form.enquiry':'Tipo di Richiesta',
      'contact.form.opt.general':'Generale','contact.form.opt.partnership':'Partnership',
      'contact.form.opt.press':'Stampa','contact.form.opt.institutional':'Istituzionale','contact.form.opt.volunteer':'Volontariato',
      'contact.form.message':'Messaggio','contact.form.btn':'Invia Messaggio',
      'contact.partner.eyebrow':'Partnership','contact.partner.h2':'Collaborazioni<br>Allineate',
      'contact.card.craft.tag':'Artigianato','contact.card.craft.h3':'Artigiani ed Esperti di Materiali',
      'contact.card.craft.p':"Collaborazioni con makers, studi e professionisti culturali allineati con la direzione artigianale raffinata della mostra.",
      'contact.card.institutional.tag':'Istituzionale','contact.card.institutional.h3':'Partner Culturali',
      'contact.card.institutional.p':'Partnership con musei, enti di design, università e istituzioni civiche.',
      'contact.card.volunteer.tag':'Team','contact.card.volunteer.h3':'Volontari',
      'contact.card.volunteer.p':"Supporto al flusso dei visitatori, alla partecipazione, all'interpretazione e alle operazioni della mostra nelle due giornate."
    },
    en: {
      // NAV
      'nav.home':'Home','nav.about':'About','nav.experience':'Experience',
      'nav.stalls':'Stalls','nav.visit':'Visit','nav.contact':'Contact','nav.cta':'Visit',
      // FOOTER
      'footer.brand.desc':'Bindi to Brera is a contemporary Indian cultural exhibition in Milan exploring craft, sensory memory, material intelligence, and participatory design.',
      'footer.h.experience':'Experience','footer.link.overview':'Overview',
      'footer.link.craft':'Craft Experiences','footer.link.material':'Material Explorations',
      'footer.link.stage':'Main Stage','footer.link.food':'Taste of India',
      'footer.h.visit':'Visit','footer.link.info':'Event Info','footer.link.venue':'Venue','footer.link.faq':'FAQ',
      'footer.h.connect':'Connect','footer.link.contact':'Contact',
      'footer.link.partners':'Partnerships','footer.link.about':'About',
      'footer.date':'Milan, Italy | 11-12 July 2026',
      // INDEX
      'index.hero.eyebrow':'Milan | 11-12 July 2026',
      'index.hero.lead':'A contemporary cultural exhibition that reframes India through craftsmanship, sensory storytelling, material intelligence, and immersive design.',
      'index.hero.meta.venue':'Venue','index.hero.meta.format':'Format','index.hero.meta.admission':'Admission',
      'index.hero.meta.format.val':'Curated Exhibition','index.hero.meta.admission.val':'Free Public Entry',
      'index.why.eyebrow':'Why Bindi to Brera','index.why.h2':'Not Geography.<br>Perception.',
      'index.why.p1':'Bindi to Brera is not a statement of geography, but of perception.',
      'index.why.p2':'While hosted at Fabbrica del Vapore, the word Brera symbolises craftsmanship, refinement, artistic sophistication, and premium cultural experience.',
      'index.why.p3':'The exhibition challenges stereotypes surrounding India by reframing it through material culture, sensory storytelling, craftsmanship, and immersive design.',
      'index.why.p4':'Bindi represents identity, intimacy, and cultural symbolism. Brera represents curation, luxury, and elevated artistic value. Together, they create a bridge between heritage and contemporary perception.',
      'index.encounters.eyebrow':'Stalls and Immersive Experiences','index.encounters.h2':'Curated Encounters',
      'index.card.craft.tag':'Craft Experiences','index.card.craft.h3':'Hands, Process, Textile',
      'index.card.craft.p':'Block printing, pottery, calligraphy, saree draping, upcycled bandana styling, rangoli wall participation, and the bindi experience.',
      'index.card.material.tag':'Material Explorations','index.card.material.h3':'Archive, Ingredient, Memory',
      'index.card.material.p':'Spice Archive, Fragrance Chamber, Ayurvedic Products, and Musical Instruments presented as material culture rather than spectacle.',
      'index.card.womb.tag':'Immersive Installation',
      'index.card.womb.p':'An immersive tunnel of origin, vibration, spatial transition, and reflection inspired by architecture and sonic philosophy.',
      'index.card.stage.tag':'Live Programme','index.card.stage.h3':'Main Stage',
      'index.card.stage.p':'Grand opening ceremony with the Consul General of India, classical Kathak and Bharatanatyam dance, Bollywood medley, and live Sitar & fusion music.',
      'index.card.food.tag':'Culinary Experience',
      'index.card.food.p':"Street-food style regional stalls spanning North, South, East, and West Indian cuisines, with a Masala Chai corner and traditional Indian sweets.",
      'index.btn.stalls':'Explore Stalls','index.btn.experience':'View Experience',
      'index.visual.eyebrow':'Visual Language','index.visual.h2':'Minimal.<br>Rich.<br>Editorial.',
      'index.visual.p':"The site now uses a restrained black, cream, muted earth, indigo, and metallic-accent palette. The mood is closer to a luxury exhibition, fashion installation, and cultural museum than an event-led spectacle.",
      'index.visit.h2':'Plan Your Visit',
      'index.visit.lead':'Two days in Milan dedicated to craft, material memory, and contemporary Indian cultural perception.',
      'index.btn.visit':'Visit Details','index.btn.contact':'Contact Us',
      'index.marquee.1':'Craftsmanship','index.marquee.2':'Material Culture','index.marquee.3':'Indian Design',
      'index.marquee.4':'Sensory Memory','index.marquee.5':'Participatory Experiences',
      'index.marquee.6':'Craftsmanship','index.marquee.7':'Material Culture','index.marquee.8':'Indian Design',
      'index.marquee.9':'Sensory Memory','index.marquee.10':'Participatory Experiences',
      // ABOUT
      'about.hero.eyebrow':'About the Exhibition',
      'about.hero.lead':'A contemporary cultural exhibition that reframes India through craftsmanship, sensory storytelling, material intelligence, and immersive design.',
      'about.name.eyebrow':'The Name','about.name.h2':'Identity Meets<br>Curation',
      'about.name.p1':'Bindi represents identity, intimacy, and cultural symbolism.',
      'about.name.p2':'Brera represents curation, luxury, and elevated artistic value.',
      'about.name.p3':"Together, they create a bridge between heritage and contemporary perception. The title is intentionally not geographic; it is a way of shifting how Indian culture is seen, handled, and valued in a European design context.",
      'about.quote':'"India is not presented as a spectacle to consume, but as a material, sensory, and intellectual world to enter with attention."',
      'about.pos.eyebrow':'Positioning','about.pos.h2':'Chic.<br>Curated.<br>Museum-like.',
      'about.pos.p1':'The exhibition moves away from decorative event language and toward an editorial, premium, contemporary experience. The focus is craft process, refined participation, ingredient histories, spatial atmosphere, and the intelligence held inside everyday materials.',
      'about.pos.p2':'Visitors are invited to observe, touch, write, print, style, listen, and reflect through designed encounters rather than decorative displays.',
      'about.lenses.eyebrow':'Core Lenses','about.lenses.h2':'How India Is Reframed',
      'about.card.craft.tag':'Craftsmanship','about.card.craft.h3':'Hands and Process',
      'about.card.craft.p':'Workshops reveal the discipline of making: pressure, rhythm, clay, textile, script, and personal adornment.',
      'about.card.material.tag':'Material Culture','about.card.material.h3':'Ingredients as Archives',
      'about.card.material.p':'Spices, botanicals, fragrance ingredients, and instruments are framed as histories of agriculture, trade, wellness, and performance.',
      'about.card.immersion.tag':'Immersion','about.card.immersion.h3':'Space and Memory',
      'about.card.immersion.p':'The Womb of OM creates a spatial transition through vibration, origin, reflection, and architectural storytelling.',
      'about.navarasa.eyebrow':'The Nine Rasas','about.navarasa.h2':'Division by<br>Emotion',
      'about.navarasa.intro':'The exhibition is structured around the nine Rasas — Sanskrit for emotional essences. Each stall and experience connects to one or more of these states, transforming the visit into an emotional journey through Indian cultural philosophy.',
      'about.rasa.srngara.h3':'Beauty','about.rasa.srngara.p':'Jewellery, Bindi, Saree Draping, Perfume.',
      'about.rasa.hasya.h3':'Play & Joy','about.rasa.hasya.p':'Block Printing, Upcycled Bandana.',
      'about.rasa.karuna.h3':'Softness & Care','about.rasa.karuna.p':'Ayurvedic Products, Pottery.',
      'about.rasa.raudra.h3':'Intensity & Heat','about.rasa.raudra.p':'Spice Archive.',
      'about.rasa.vira.h3':'Energy & Mastery','about.rasa.vira.p':'Block Printing, Saree Draping, Calligraphy.',
      'about.rasa.bhayanka.h3':'Awe & Overwhelm','about.rasa.bhayanka.p':'The Womb of OM.',
      'about.rasa.adhbutha.h3':'Wonder & Discovery','about.rasa.adhbutha.p':'Musical Instruments, Block Printing, Calligraphy.',
      'about.rasa.bibhatsa.h3':'Raw Material Truth','about.rasa.bibhatsa.p':'Spices, Pottery, Ayurvedic raw ingredients.',
      'about.rasa.santa.h3':'Calm & Balance','about.rasa.santa.p':'Ayurvedic Products.',
      'about.notfair.h2':'Not a Fair.<br>An Exhibition.',
      'about.notfair.p':'The updated direction uses refined cultural interpretation, restrained visual rhythm, and visitor participation with purpose. The experience is now structured around craft intelligence, material culture, and contemporary perception.',
      'about.btn.experience':'Experience Overview',
      // EXPERIENCE
      'exp.hero.eyebrow':'The Emotional Framework','exp.hero.h1':'Nine<br>Rasas',
      'exp.hero.p':'The exhibition is structured around the nine Rasas — Sanskrit emotional essences from Indian aesthetic philosophy. Every stall, workshop, and installation maps to one or more of these states.',
      'exp.what.eyebrow':'What Is a Rasa','exp.what.h2':'Feeling<br>as<br>Framework',
      'exp.what.p1':'Rasa — Sanskrit for "essence" or "flavour" — is a 2,000-year-old Indian aesthetic concept describing the emotional states that art and experience can evoke. The nine Rasas form the basis of classical Indian performing arts, poetry, and design.',
      'exp.what.p2':'Bindi to Brera uses this framework to organise the exhibition. Every encounter — from block printing to the Womb of OM — is intentionally placed within an emotional register. The result is not a cultural display but an emotional journey through Indian aesthetic philosophy.',
      'exp.btn.stalls':'Explore All Stalls',
      'exp.rasas.eyebrow':'The Nine Emotional States','exp.rasas.h2':'The Rasas',
      'exp.rasa.srngara.h3':'Beauty',
      'exp.rasa.srngara.p':'The rasa of adornment, intimacy, and sensory pleasure. The world seen through the lens of beauty and desire.',
      'exp.rasa.srngara.links':'→ <a href="stalls.html#jewellery" style="color:inherit">Indian Jewellery</a> · <a href="stalls.html#bindi" style="color:inherit">Bindi &amp; Tattoo</a> · <a href="stalls.html#saree" style="color:inherit">Saree Draping</a> · <a href="stalls.html#fragrance-chamber" style="color:inherit">Fragrance Chamber</a>',
      'exp.rasa.hasya.h3':'Play & Joy',
      'exp.rasa.hasya.p':'The rasa of laughter, lightness, and playful creation — when making mistakes becomes part of the joy.',
      'exp.rasa.hasya.links':'→ <a href="stalls.html#block" style="color:inherit">Block Printing</a> · <a href="stalls.html#bandana" style="color:inherit">Upcycled Bandana</a>',
      'exp.rasa.karuna.h3':'Softness & Care',
      'exp.rasa.karuna.p':'The rasa of compassion and tenderness — the therapeutic process of making, healing, and nurturing.',
      'exp.rasa.karuna.links':'→ <a href="stalls.html#ayurvedic-products" style="color:inherit">Ayurvedic Products</a> · <a href="stalls.html#pottery" style="color:inherit">Live Pottery</a>',
      'exp.rasa.raudra.h3':'Intensity & Heat',
      'exp.rasa.raudra.p':"The rasa of force, passion, and raw energy — the overwhelming heat and power of India's material world.",
      'exp.rasa.raudra.links':'→ <a href="stalls.html#spice-archive" style="color:inherit">Spice Archive</a>',
      'exp.rasa.vira.h3':'Energy & Mastery',
      'exp.rasa.vira.p':'The rasa of skill, confidence, and disciplined action — craft performed with precision and transformative power.',
      'exp.rasa.vira.links':'→ <a href="stalls.html#block" style="color:inherit">Block Printing</a> · <a href="stalls.html#saree" style="color:inherit">Saree Draping</a> · <a href="stalls.html#calligraphy" style="color:inherit">Calligraphy</a>',
      'exp.rasa.bhayanka.h3':'Awe & the Unknown',
      'exp.rasa.bhayanka.p':'The rasa of overwhelm and mystery — the confrontation with something larger than the self.',
      'exp.rasa.bhayanka.links':'→ <a href="stalls.html#womb-of-om" style="color:inherit">The Womb of OM</a>',
      'exp.rasa.adhbutha.h3':'Wonder & Discovery',
      'exp.rasa.adhbutha.p':'The rasa of astonishment — when a pattern emerges, a language transforms visually, a sound is felt physically.',
      'exp.rasa.adhbutha.links':'→ <a href="stalls.html#musical-instruments" style="color:inherit">Musical Instruments</a> · <a href="stalls.html#block" style="color:inherit">Block Printing</a> · <a href="stalls.html#calligraphy" style="color:inherit">Calligraphy</a>',
      'exp.rasa.bibhatsa.h3':'Raw Material Truth',
      'exp.rasa.bibhatsa.p':'The rasa of the unprocessed and unrefined — matter in its origin state before it becomes commodity or luxury.',
      'exp.rasa.bibhatsa.links':'→ <a href="stalls.html#spice-archive" style="color:inherit">Spice Archive</a> · <a href="stalls.html#pottery" style="color:inherit">Live Pottery</a> · <a href="stalls.html#ayurvedic-products" style="color:inherit">Ayurvedic Products</a>',
      'exp.rasa.santa.h3':'Calm & Balance',
      'exp.rasa.santa.p':'The rasa of peace and equanimity — rest, sensory reset, and the quiet that follows full engagement.',
      'exp.rasa.santa.links':'→ <a href="stalls.html#ayurvedic-products" style="color:inherit">Ayurvedic Products</a>',
      'exp.ready.h2':'Ready to<br>Explore?',
      'exp.ready.p':'Each stall and installation connects to one or more of these emotional states. Visit the full stalls directory to see every experience in detail.',
      'exp.btn.stalls2':'See All Stalls','exp.btn.about':'About the Nine Rasas',
      // STALLS
      'stalls.hero.eyebrow':'Approved Experience Set','stalls.hero.h1':'Stalls and<br>Immersive<br>Experiences',
      'stalls.hero.p':'A focused programme of craft participation, material culture, sound, fragrance, botanical knowledge, and spatial reflection.',
      'stalls.craft.eyebrow':'Craft Experiences','stalls.craft.h2':'Participatory Making',
      'stalls.card.block.tag':'Workshop','stalls.card.block.h3':'Block Printing Workshop',
      'stalls.card.block.p':'Collaborative textile printing where visitors self-print, experience the pressure of the block, and add to a shared textile surface.',
      'stalls.card.pottery.tag':'Live Making','stalls.card.pottery.h3':'Pottery',
      'stalls.card.pottery.p':'Live clay making shaped as storytelling through craft, earth, hand, form, and inherited technique.',
      'stalls.card.calligraphy.tag':'Script','stalls.card.calligraphy.h3':'Calligraphy',
      'stalls.card.calligraphy.p':'Indian language exploration with visitor participation through writing, stencils, and guided mark-making.',
      'stalls.card.saree.tag':'Textile','stalls.card.saree.h3':'Saree Draping',
      'stalls.card.saree.p':'Contemporary draping exploration that treats six yards of fabric as design, identity, sculpture, and personal movement.',
      'stalls.card.bandana.tag':'Sustainable Styling','stalls.card.bandana.h3':'Upcycled Bandana',
      'stalls.card.bandana.p':'A sustainable styling experience using textile reuse for fashion experimentation and personal expression.',
      'stalls.card.rangoli.tag':'Wall Installation','stalls.card.rangoli.h3':'Rangoli Wall',
      'stalls.card.rangoli.p':'A collective wall installation where each visitor contributes through sticker placement, plus a public Rangoli sand-art competition open to all ages.',
      'stalls.card.bindi.tag':'Adornment','stalls.card.bindi.h3':'Bindi & Temporary Tattoo',
      'stalls.card.bindi.p':'Interactive beauty station with bindis in varied shapes, colours, and designs, plus small hand-painted motifs around the eyes and forehead inspired by henna and traditional Indian art.',
      'stalls.material.eyebrow':'Material and Cultural Explorations','stalls.material.h2':'Archives of Matter',
      'stalls.card.spice.tag':'Material Culture','stalls.card.spice.h3':'Spice Archive',
      'stalls.card.spice.p':'Spices are presented through agricultural heritage, colour, texture, and global trade significance.',
      'stalls.card.fragrance.tag':'Natural Perfumery','stalls.card.fragrance.h3':'Fragrance Chamber',
      'stalls.card.fragrance.p':'Material ingredients, craftsmanship, memory, and cultural storytelling through fragrance history.',
      'stalls.card.ayurveda.tag':'Botanical Knowledge','stalls.card.ayurveda.h3':'Ayurvedic Products',
      'stalls.card.ayurveda.p':'Beauty and wellness traditions presented through ingredient exploration and material heritage.',
      'stalls.card.music.tag':'Interactive Sound','stalls.card.music.h3':'Musical Instruments',
      'stalls.card.music.p':'Craftsmanship of instrument-making, resonance, tactile rhythm exploration, performance traditions, and visitor interaction.',
      'stalls.card.jewellery.tag':'Jewellery','stalls.card.jewellery.h3':'Indian Jewellery',
      'stalls.card.jewellery.p':'A curated collection of traditional and contemporary jewellery — jhumkas, bangles, anklets, nose rings, and layered necklaces inspired by different regions of India.',
      'stalls.stage.eyebrow':'Live Programme','stalls.stage.h2':'Main<br>Stage',
      'stalls.stage.p1':'The centrepiece of the event. Opens with a formal ceremony featuring the Consul General of India and a Comune di Milano representative.',
      'stalls.stage.p2':'Followed by classical Kathak and Bharatanatyam dance, a professional Bollywood medley troupe, and a live Sitar & fusion music ensemble.',
      'stalls.stage.item1.h3':'Grand Opening Ceremony','stalls.stage.item1.p':'Consul General of India & Comune di Milano representative.',
      'stalls.stage.item2.h3':'Kathak & Bharatanatyam','stalls.stage.item2.p':'Classical Indian dance performances.',
      'stalls.stage.item3.h3':'Bollywood Medley Troupe','stalls.stage.item3.p':'Professional contemporary Bollywood performance.',
      'stalls.stage.item4.h3':'Sitar & Fusion Ensemble','stalls.stage.item4.p':'Live music performance.',
      'stalls.food.eyebrow':'Culinary Experience','stalls.food.h2':'Taste<br>of India',
      'stalls.food.p1':"A street-food style area with regional stalls covering North, South, East, and West Indian cuisines. A live dialogue between India's culinary heritage and Milan's food culture.",
      'stalls.food.p2':'Includes a Masala Chai corner and traditional Indian sweets. All operators hold valid food permits, and eco-friendly packaging is required throughout.',
      'stalls.womb.eyebrow':'Immersive Installation','stalls.womb.h2':'The Womb<br>of OM',
      'stalls.womb.p1':'"OM" is treated as the form of the universe — a continuous cycle of creation, existence, and return.',
      'stalls.womb.p2':'Inspired by ancient temple carvings where life is shown emerging within sacred sound forms, the installation reflects the idea of origin held inside the symbol itself.',
      'stalls.womb.p3':'The umbilical cord becomes the visual thread of life, connecting beginning and becoming in one unbroken flow.',
      'stalls.womb.p4':'The stall translates this into an immersive experience where the body moves through cycles of birth, growth, and return.',
      // VISIT
      'visit.hero.eyebrow':'Plan Your Visit','visit.hero.h1':'Milan<br>2026',
      'visit.hero.p':'All practical details for attending Bindi to Brera, a free public exhibition at Fabbrica del Vapore.',
      'visit.details.eyebrow':'Event Details','visit.details.h2':'11-12 July<br>2026',
      'visit.detail.venue.label':'Venue','visit.detail.venue.val':'Fabbrica del Vapore or Parco Sempione, Milan (subject to Comune availability)',
      'visit.detail.admission.label':'Admission','visit.detail.admission.val':'Free public entry',
      'visit.detail.format.label':'Format','visit.detail.format.val':'Open-air and indoor multicultural public exhibition',
      'visit.detail.focus.label':'Focus','visit.detail.focus.val':'Craft, material culture, immersion',
      'visit.detail.audience.label':'Audience','visit.detail.audience.val':'Milanese citizens, Italian public & the 50,000+ Indian diaspora in Lombardy',
      'visit.detail.duration.label':'Duration','visit.detail.duration.val':'Two days',
      'visit.detail.attendance.label':'Expected Attendance','visit.detail.attendance.val':'2,000–5,000 visitors',
      'visit.detail.patronage.label':'Civic Patronage','visit.detail.patronage.val':'Comune di Milano',
      'visit.expect.eyebrow':'What to Expect','visit.expect.h2':'A Slower<br>Encounter',
      'visit.expect.p1':"Visitors can move between craft experiences, material and cultural explorations, the live Main Stage performances, the Taste of India food court, and the Womb of OM installation. The programme is designed for close looking, careful participation, and contemporary cultural interpretation.",
      'visit.expect.p2':'Some hands-on experiences may have limited capacity at peak times, but the exhibition is built for walk-in discovery throughout the day.',
      'visit.faq.eyebrow':'FAQ','visit.faq.h2':'Good to Know',
      'visit.faq.free.h3':'Is entry free?','visit.faq.free.p':'Yes. The exhibition is free and open to the public.',
      'visit.faq.venue.h3':'Where is the venue?','visit.faq.venue.p':'The exhibition is planned for Fabbrica del Vapore in Milan.',
      'visit.faq.book.h3':'Are experiences bookable?','visit.faq.book.p':'Most experiences are walk-in. Capacity may be managed on site for comfort and quality.',
      'visit.faq.time.h3':'How long should I stay?','visit.faq.time.p':'Plan at least two hours for the core route, or longer if you want to participate in several craft experiences.',
      'visit.questions.h2':'Questions?','visit.questions.lead':'For partnerships, press, or visitor information, contact the team.',
      'visit.btn.contact':'Contact Us','visit.reg.h3':'Register Your Visit',
      'visit.reg.name':'Name','visit.reg.email':'Email','visit.reg.attendees':'Number of Attendees','visit.reg.btn':'Register',
      // CONTACT
      'contact.hero.eyebrow':'Contact','contact.hero.h1':'Work<br>With Us',
      'contact.hero.p':'For partnerships, press, institutional enquiries, or visitor information, reach the Bindi to Brera team.',
      'contact.info.eyebrow':'Contact Information','contact.info.h2':"Let's<br>Connect",
      'contact.info.general.h3':'General Enquiries','contact.info.support.h3':'Support',
      'contact.info.partners.h3':'Partnerships','contact.info.location.h3':'Location',
      'contact.info.location.val':'Fabbrica del Vapore, Milan | 11-12 July 2026',
      'contact.form.name':'Name','contact.form.email':'Email',
      'contact.form.enquiry':'Type of Enquiry',
      'contact.form.opt.general':'General','contact.form.opt.partnership':'Partnership',
      'contact.form.opt.press':'Press','contact.form.opt.institutional':'Institutional','contact.form.opt.volunteer':'Volunteer',
      'contact.form.message':'Message','contact.form.btn':'Send Message',
      'contact.partner.eyebrow':'Partnerships','contact.partner.h2':'Aligned<br>Collaborations',
      'contact.card.craft.tag':'Craft','contact.card.craft.h3':'Artisans and Material Experts',
      'contact.card.craft.p':"Collaborations with makers, studios, and cultural practitioners aligned with the exhibition's refined craft direction.",
      'contact.card.institutional.tag':'Institutional','contact.card.institutional.h3':'Cultural Partners',
      'contact.card.institutional.p':'Partnerships with museums, design bodies, universities, and civic institutions.',
      'contact.card.volunteer.tag':'Team','contact.card.volunteer.h3':'Volunteers',
      'contact.card.volunteer.p':'Support visitor flow, participation, interpretation, and exhibition operations across the two days.'
    }
  };

  var pageTitles = {
    it:{
      'index.html':'Bindi to Brera | Mostra Culturale Indiana Milano 2026',
      'about.html':'Chi Siamo | Bindi to Brera',
      'experience.html':'Esperienza | Bindi to Brera',
      'stalls.html':'Mostre ed Esperienze Immersive | Bindi to Brera',
      'visit.html':'Visita | Bindi to Brera',
      'contact.html':'Contatti | Bindi to Brera'
    },
    en:{
      'index.html':'Bindi to Brera | Indian Cultural Exhibition Milan 2026',
      'about.html':'About | Bindi to Brera',
      'experience.html':'Experience | Bindi to Brera',
      'stalls.html':'Stalls and Immersive Experiences | Bindi to Brera',
      'visit.html':'Visit | Bindi to Brera',
      'contact.html':'Contact | Bindi to Brera'
    }
  };

  var currentLang = localStorage.getItem('btb-lang') || 'it';

  function applyLanguage(lang){
    currentLang = lang;
    localStorage.setItem('btb-lang', lang);
    document.documentElement.lang = lang;
    var d = T[lang];
    document.querySelectorAll('[data-i18n]').forEach(function(el){
      var key = el.getAttribute('data-i18n');
      if(d[key] !== undefined) el.innerHTML = d[key];
    });
    var page = (window.location.pathname.split('/').pop() || 'index.html') || 'index.html';
    if(pageTitles[lang][page]) document.title = pageTitles[lang][page];
    var toggleBtn = document.getElementById('lang-toggle');
    if(toggleBtn) toggleBtn.textContent = lang === 'it' ? 'EN' : 'IT';
  }

  applyLanguage(currentLang);

  var langBtn = document.getElementById('lang-toggle');
  if(langBtn){
    langBtn.addEventListener('click', function(){
      applyLanguage(currentLang === 'it' ? 'en' : 'it');
    });
  }
})();
